### ISSUE TITLE
https://replicate.com/nightmareai/real-esrgan

### ISSUE THREAD

**Issue by MichalAniol** [MichalAniol/home_page#480]
https://replicate.com/nightmareai/real-esrgan

**Comment by kyawsoe7** [comment]
![out.jpg](https://github.com/MichalAniol/home_page/assets/153421259/cfa390e6-c373-4f5f-ad91-6081b4730b71)

**Comment by kyawsoe7** [comment]
![received_160623290429259](https://github.com/MichalAniol/home_page/assets/153421259/faa1e5b3-d5e8-47ad-baf0-2902aeb94552)
